spring:
  application:
    name: 'eureka-server'
  config:
    import: 'configserver:'
  cloud:
    config:
      uri: ${config_uri}
      username: ${config_username}
      password: ${config_password}
  security:
    user:
      name: ${security.username}
      password: ${security.password}
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: ${url}
  server:
    peer-node-connect-timeout-ms: 20000
    peer-node-read-timeout-ms: 20000
server:
  port: 8761