CREATE SEQUENCE IF NOT EXISTS announcement_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS announcements_images_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS announcements_likes_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS announcements_watches_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS reports_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE announcements
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner_id     BIGINT                                  NOT NULL,
    title        VARCHAR                                 NOT NULL,
    description  VARCHAR,
    price        DOUBLE PRECISION                        NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    type         VARCHAR                                 NOT NULL,
    phone_number VARCHAR                                 NOT NULL,
    country      VARCHAR                                 NOT NULL,
    city         VARCHAR                                 NOT NULL,
    likes        INTEGER                                 NOT NULL,
    watches      INTEGER DEFAULT 0                       NOT NULL,
    CONSTRAINT announcement_pkey PRIMARY KEY (id)
);

CREATE TABLE announcements_images
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    file_name       VARCHAR                                 NOT NULL,
    announcement_id BIGINT                                  NOT NULL,
    CONSTRAINT announcements_images_pkey PRIMARY KEY (id)
);

CREATE TABLE announcements_likes
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    announcement_id BIGINT                                  NOT NULL,
    user_id         BIGINT                                  NOT NULL,
    CONSTRAINT announcements_likes_pkey PRIMARY KEY (id)
);

CREATE TABLE announcements_watches
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    announcement_id BIGINT                                  NOT NULL,
    user_id         BIGINT                                  NOT NULL,
    CONSTRAINT announcements_watches_pkey PRIMARY KEY (id)
);

CREATE TABLE reports
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    announcement_id BIGINT                                  NOT NULL,
    cause           VARCHAR                                 NOT NULL,
    sender_id       BIGINT                                  NOT NULL,
    CONSTRAINT reports_pkey PRIMARY KEY (id)
);

ALTER TABLE announcements_images
    ADD CONSTRAINT announcements_images_announcement_id_fkey FOREIGN KEY (announcement_id) REFERENCES announcements (id) ON DELETE CASCADE;

ALTER TABLE announcements_likes
    ADD CONSTRAINT announcements_likes_announcement_id_fkey FOREIGN KEY (announcement_id) REFERENCES announcements (id) ON DELETE CASCADE;

ALTER TABLE announcements_watches
    ADD CONSTRAINT announcements_watches_announcement_id_fkey FOREIGN KEY (announcement_id) REFERENCES announcements (id) ON DELETE CASCADE;

ALTER TABLE reports
    ADD CONSTRAINT reports_announcement_id_fkey FOREIGN KEY (announcement_id) REFERENCES announcements (id) ON DELETE CASCADE;