CREATE SEQUENCE IF NOT EXISTS chats_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS chats_messages_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS support_chats_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS support_chats_messages_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE chats
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user1_id BIGINT                                  NOT NULL,
    user2_id BIGINT                                  NOT NULL,
    CONSTRAINT chats_pkey PRIMARY KEY (id)
);

CREATE TABLE chats_messages
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    chat_id      BIGINT                                  NOT NULL,
    sender_id    BIGINT                                  NOT NULL,
    text         VARCHAR                                 NOT NULL,
    sent_time    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    content_type VARCHAR                                 NOT NULL,
    CONSTRAINT chats_messages_pkey PRIMARY KEY (id)
);

CREATE TABLE support_chats
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id  BIGINT                                  NOT NULL,
    status   VARCHAR                                 NOT NULL,
    admin_id BIGINT,
    CONSTRAINT support_chats_pkey PRIMARY KEY (id)
);

CREATE TABLE support_chats_messages
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text         VARCHAR                                 NOT NULL,
    sender_id    BIGINT                                  NOT NULL,
    sent_time    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    content_type VARCHAR                                 NOT NULL,
    chat_id      BIGINT                                  NOT NULL,
    CONSTRAINT support_chats_messages_pkey PRIMARY KEY (id)
);

ALTER TABLE chats
    ADD CONSTRAINT chats_user1_id_user2_id_key UNIQUE (user1_id, user2_id);

ALTER TABLE chats_messages
    ADD CONSTRAINT chats_messages_chat_id_fkey FOREIGN KEY (chat_id) REFERENCES chats (id) ON DELETE CASCADE;

ALTER TABLE support_chats_messages
    ADD CONSTRAINT support_chats_messages_chat_id_fkey FOREIGN KEY (chat_id) REFERENCES support_chats (id) ON DELETE CASCADE;