spring:
  application:
    name: 'users-service'
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${db.username}
    password: ${db.password}
    url: ${db.url}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${jwt.issuer-uri}
          jwk-set-uri: ${jwt.jwk-set-uri}
  flyway:
    locations: classpath:db_migration
  servlet:
    multipart:
      max-file-size: ${max-file-size}
      max-request-size: ${max-file-size}
  kafka:
    consumer:
      bootstrap-servers: ${kafka.host}:${kafka.port}
  config:
    import: 'configserver:'
  cloud:
    openfeign:
      okhttp:
        enabled: true
    discovery:
      enabled: true
    config:
      uri: ${config_uri}
      username: ${config_username}
      password: ${config_password}
server:
  port: 9090
avatar:
  default: ${default-avatar}
springdoc:
  swagger-ui:
    enabled: true
    path: /users/swagger-ui/index.html
  api-docs:
    enabled: true
    path: /users/v3/api-docs
eureka:
  instance:
    instanceId: ${spring.application.name}
    hostname: ${eureka.client.hostname}
    preferIpAddress: false
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${eureka.server.url}
allowed_origins: ${allowed_origins}
access_key: ${access_key}
temp-users_storage_time: ${temp-users_storage_time}
kafka-topics:
  deleted-user: ${kafka.topics.deleted-user}
  email-message: ${kafka.topics.email-message}
redis:
  host: ${redis.host}
  port: ${redis.port}
  password: ${redis.password}
  username: ${redis.username}
  database: ${redis.database}
jwt:
  principal-attribute: ${jwt.principal-attribute}
  resource-id: ${jwt.resource-id}
management:
  endpoints:
    web:
      exposure:
        include: refresh