services:
  config-server:
    build:
      context: .
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/DAN1X27/items-sales-service-configuration
      - SPRING_SECURITY_USER_NAME=username
      - SPRING_SECURITY_USER_PASSWORD=password
    ports:
      - "8888:8888"
    networks:
      - items-sales-service-net
networks:
  items-sales-service-net:
    external: true
    name: items-sales-service-net