services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.2.5
    container_name: keycloak
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KEYCLOAK_IMPORT=/opt/keycloak/data/import/realm.json
    volumes:
      - ./realm.json:/opt/keycloak/data/import/realm.json
    command: ["start-dev", "--http-port=8081", "--import-realm"]
    ports:
      - 8081:8081
    networks:
      - items-sales-service-net
    restart: unless-stopped
networks:
  items-sales-service-net:
    external: true
    name: items-sales-service-net