spring:
  application:
    name: gateway-service
  config:
    import: 'configserver:'
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: ${allowed_origins}
            allowedHeaders: "*"
            allow-credentials: true
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - PATCH
              - OPTIONS
    config:
      uri: ${config_uri}
      username: ${config_username}
      password: ${config_password}
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
    urls:
      - name: Announcements service API
        url: /announcements/v3/api-docs
      - name: Authentication service API
        url: /auth/v3/api-docs
      - name: Chats service API
        url: /chats/v3/api-docs
      - name: Users service API
        url: /users/v3/api-docs
eureka:
  instance:
    instanceId: ${spring.application.name}
    hostname: ${eureka.client.hostname}
    preferIpAddress: false
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${eureka.server.url}
management:
  endpoints:
    web:
      exposure:
        include: refresh