services:
  eureka-server:
    build:
      context: .
    environment:
      - SPRING_SECURITY_USER_NAME=username
      - SPRING_SECURITY_USER_PASSWORD=password
    ports:
      - "8761:8761"
    networks:
      - items-sales-service-net
networks:
  items-sales-service-net:
    external: true
    name: items-sales-service-net