server:
  port: 6060
spring:
  application:
    name: 'authentication-service'
  kafka:
    consumer:
      bootstrap-servers: ${kafka.host}:${kafka.port}
      group-id: ${kafka.group-id}
  config:
    import: 'configserver:'
  cloud:
    config:
      uri: ${config-uri}
      username: ${config-username}
      password: ${config-password}
    openfeign:
      okhttp:
        enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${jwt.issuer-uri}
          jwk-set-uri: ${jwt.jwk-set-uri}
redis:
  host: ${redis.host}
  port: ${redis.port}
  password: ${redis.password}
  username: ${redis.username}
  database: ${redis.database}
email-keys-storage-time-minutes: ${email-keys-storage-time-minutes}
max-email-key-attempts: ${max-email-key-attempts}
tokens-storage-days: ${tokens-storage-days}
allowed_origins: ${allowed_origins}
springdoc:
  api-docs:
    enabled: true
    path: /auth/v3/api-docs
  swagger-ui:
    enabled: true
    path: /auth/swagger-ui/index.html
eureka:
  instance:
    instanceId: ${spring.application.name}
    hostname: ${eureka.client.hostname}
    preferIpAddress: false
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${eureka.server.url}
keycloak:
  url: ${keycloak.url}
  client-id: ${keycloak.client-id}
  client-secret: ${keycloak.client-secret}
  admin-client-id: ${keycloak.admin-client-id}
  admin-client-secret: ${keycloak.admin-client-secret}
jwt:
  resource-id: ${jwt.resource-id}
  principal-attribute: ${jwt.principal-attribute}
access_key: ${access_key}
management:
  endpoints:
    web:
      exposure:
        include: refresh