server:
  port: 6565
spring:
  application:
    name: 'email-sender-service'
  mail:
    host: ${mail.host}
    port: ${mail.port}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: ${mail.username}
    password: ${mail.password}
  config:
    import: 'configserver:'
  cloud:
    config:
      uri: ${config_uri}
      username: ${config_username}
      password: ${config_password}
  kafka:
    consumer:
      bootstrap-servers: ${kafka.host}:${kafka.port}
      group-id: ${kafka.group_id}
management:
  endpoints:
    web:
      exposure:
        include: refresh