spring:
  flyway:
    locations: classpath:db_migration
  application:
    name: 'chats-service'
  config:
    import: 'configserver:'
  cloud:
    config:
      uri: ${config_uri}
      username: ${config_username}
      password: ${config_password}
  servlet:
    multipart:
      max-file-size: ${max_file_size}
      max-request-size: ${max_file_size}
  kafka:
    consumer:
      bootstrap-servers: ${kafka.host}:${kafka.port}
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${jwt.issuer-uri}
          jwk-set-uri: ${jwt.jwk-set-uri}
eureka:
  instance:
    instanceId: ${spring.application.name}
    hostname: ${eureka.client.hostname}
    preferIpAddress: false
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${eureka.server.url}
springdoc:
  api-docs:
    enabled: true
    path: /chats/v3/api-docs
  swagger-ui:
    enabled: true
    path: /chats/swagger-ui/index.html
jwt:
  principal-attribute: ${jwt.principal-attribute}
  resource-id: ${jwt.resource-id}
allowed_origins: ${allowed_origins}
access_key: ${access_key}
server:
  port: 8085
management:
  endpoints:
    web:
      exposure:
        include: refresh