services:
  authentication-service:
    build:
      context: .
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_CLOUD_CONFIG_USERNAME=username
      - SPRING_CLOUD_CONFIG_PASSWORD=password
    ports:
      - "6060:6060"
    networks:
      - items-sales-service-net
networks:
  items-sales-service-net:
    external: true
    name: items-sales-service-net