services:
  files-service:
    build:
      context: .
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_CLOUD_CONFIG_USERNAME=username
      - SPRING_CLOUD_CONFIG_PASSWORD=password
      - PATHS_USERS_AVATARS=/app/files/users_avatars
      - PATHS_CHATS_IMAGES=/app/files/chats_images
      - PATHS_CHATS_VIDEOS=/app/files/chats/videos
      - PATHS_ANNOUNCEMENTS_IMAGES=/app/files/announcements_images
    ports:
      - "8084:8084"
    networks:
      - items-sales-service-net
networks:
  items-sales-service-net:
    external: true
    name: items-sales-service-net