services:
  chats-service:
    build:
      context: .
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_CLOUD_CONFIG_USERNAME=username
      - SPRING_CLOUD_CONFIG_PASSWORD=password
    networks:
      - items-sales-service-net
    ports:
      - "8085:8085"
networks:
  items-sales-service-net:
    external: true
    name: items-sales-service-net