CREATE SEQUENCE IF NOT EXISTS banned_users_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS blocked_users_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS comments_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS grades_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS reports_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS users_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE banned_users
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT                                   NOT NULL,
    cause   VARCHAR                                  NOT NULL,
    CONSTRAINT banned_users_pkey PRIMARY KEY (user_id)
);

CREATE TABLE blocked_users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner_id BIGINT                                  NOT NULL,
    user_id  BIGINT                                  NOT NULL,
    CONSTRAINT blocked_users_pkey PRIMARY KEY (id)
);

CREATE TABLE comments
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text       VARCHAR                                 NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    owner_id   BIGINT                                  NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    CONSTRAINT comments_pkey PRIMARY KEY (id)
);

CREATE TABLE grades
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    stars    INTEGER                                 NOT NULL,
    owner_id BIGINT                                  NOT NULL,
    user_id  BIGINT                                  NOT NULL,
    CONSTRAINT grades_pkey PRIMARY KEY (id)
);

CREATE TABLE reports
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cause      VARCHAR                                  NOT NULL,
    user_id    BIGINT                                   NOT NULL,
    sender_id  BIGINT                                   NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    CONSTRAINT reports_pkey PRIMARY KEY (id)
);

CREATE TABLE users
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY                   NOT NULL,
    username      VARCHAR                                                    NOT NULL,
    email         VARCHAR                                                    NOT NULL,
    password      VARCHAR                                                    NOT NULL,
    status        VARCHAR                                                    NOT NULL,
    role          VARCHAR                                                    NOT NULL,
    registered_at TIMESTAMP WITHOUT TIME ZONE                                NOT NULL,
    avatar        VARCHAR DEFAULT '3a2cd62f-121a-48b5-b0aa-e54454d4d996.jpg' NOT NULL,
    country       VARCHAR DEFAULT 'Belarus'                                  NOT NULL,
    city          VARCHAR DEFAULT 'Minsk'                                    NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

ALTER TABLE banned_users
    ADD CONSTRAINT banned_users_id_key UNIQUE (id);

ALTER TABLE blocked_users
    ADD CONSTRAINT blocked_users_owner_id_user_id_key UNIQUE (owner_id, user_id);

ALTER TABLE users
    ADD CONSTRAINT users_email_key UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT users_username_key UNIQUE (username);

ALTER TABLE banned_users
    ADD CONSTRAINT banned_users_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE blocked_users
    ADD CONSTRAINT blocked_users_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE blocked_users
    ADD CONSTRAINT blocked_users_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE comments
    ADD CONSTRAINT comments_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE comments
    ADD CONSTRAINT comments_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE grades
    ADD CONSTRAINT grades_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE grades
    ADD CONSTRAINT grades_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE reports
    ADD CONSTRAINT reports_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE reports
    ADD CONSTRAINT reports_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;