name: PR Build

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'DAN1X27/items-sales-service'

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
      - name: announcements-service maven build
        run: mvn --batch-mode --update-snapshots verify -f ./announcements-service/pom.xml
      - name: users-service maven build
        run: mvn --batch-mode --update-snapshots verify -f ./users-service/pom.xml